name: Python application

on:
  schedule:
    - cron: '40 23 * * 0-4' #北京时间 07:20 → UTC 时间 23:20,utc时间周日到周四，加8北京时间周一到周五
    - cron: '13 10 * * 1-5'
  workflow_dispatch:  # 允许手动触发工作流


permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests #默认环境没有requests库
        
    - name: run python script
      run: python main.py --username ${{ secrets.USERNAME }} --password ${{ secrets.PASSWORD }} --check_address ${{ secrets.CHECK_ADDRESS }} --latitude ${{ secrets.LATITUDE }} --longitude ${{ secrets.LONGITUDE }} --iyuuapi ${{ secrets.IYUUAPI }}
